development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://vpavlrjlwowrjh:bd7737295628c913f9a48f91ba96559b5ffac6074f313b2b6916b863ef570f0f@ec2-174-129-192-200.compute-1.amazonaws.com:5432/d1uorbaqnjc237
  channel_prefix: three_dash_seven-T_production
